[2021-03-22 17:18:03,386] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: test_slack.send_slack 2021-03-22T07:21:00+00:00 [queued]>
[2021-03-22 17:18:03,392] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: test_slack.send_slack 2021-03-22T07:21:00+00:00 [queued]>
[2021-03-22 17:18:03,392] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-03-22 17:18:03,393] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-03-22 17:18:03,393] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-03-22 17:18:03,399] {taskinstance.py:1063} INFO - Executing <Task(SlackAPIPostOperator): send_slack> on 2021-03-22T07:21:00+00:00
[2021-03-22 17:18:03,401] {standard_task_runner.py:52} INFO - Started process 16759 to run task
[2021-03-22 17:18:03,409] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'test_slack', 'send_slack', '2021-03-22T07:21:00+00:00', '--job-id', '41', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/slack.py', '--cfg-path', '/var/folders/1l/hpssfvcn1z7dpsnpgtc10rlw0000gn/T/tmp37pu4kt2', '--error-file', '/var/folders/1l/hpssfvcn1z7dpsnpgtc10rlw0000gn/T/tmp73gk5b7c']
[2021-03-22 17:18:03,412] {standard_task_runner.py:77} INFO - Job 41: Subtask send_slack
[2021-03-22 17:18:03,453] {logging_mixin.py:104} INFO - Running <TaskInstance: test_slack.send_slack 2021-03-22T07:21:00+00:00 [running]> on host Choui-MacBook-Pro.local
[2021-03-22 17:18:03,483] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=hana
AIRFLOW_CTX_DAG_ID=test_slack
AIRFLOW_CTX_TASK_ID=send_slack
AIRFLOW_CTX_EXECUTION_DATE=2021-03-22T07:21:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-03-22T07:21:00+00:00
[2021-03-22 17:18:04,095] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=test_slack, task_id=send_slack, execution_date=20210322T072100, start_date=20210322T081803, end_date=20210322T081804
[2021-03-22 17:18:04,119] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-03-22 17:18:04,155] {local_task_job.py:146} INFO - Task exited with return code 0
